// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Action(arg1) {
  return window['go']['main']['App']['Action'](arg1);
}

export function CheckAction(arg1, arg2) {
  return window['go']['main']['App']['CheckAction'](arg1, arg2);
}

export function CheckWorkflow(arg1, arg2) {
  return window['go']['main']['App']['CheckWorkflow'](arg1, arg2);
}

export function Choose() {
  return window['go']['main']['App']['Choose']();
}

export function Initial() {
  return window['go']['main']['App']['Initial']();
}

export function Project() {
  return window['go']['main']['App']['Project']();
}

export function RenderAction(arg1) {
  return window['go']['main']['App']['RenderAction'](arg1);
}

export function RenderWorkflow(arg1) {
  return window['go']['main']['App']['RenderWorkflow'](arg1);
}

export function Run(arg1, arg2, arg3) {
  return window['go']['main']['App']['Run'](arg1, arg2, arg3);
}

export function SaveAction(arg1, arg2) {
  return window['go']['main']['App']['SaveAction'](arg1, arg2);
}

export function SaveWorkflow(arg1, arg2) {
  return window['go']['main']['App']['SaveWorkflow'](arg1, arg2);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function Workflow(arg1) {
  return window['go']['main']['App']['Workflow'](arg1);
}
