// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {doc} from '../models';
import {studio} from '../models';

export function Action(arg1:string):Promise<doc.Action>;

export function CheckAction(arg1:string,arg2:doc.Action):Promise<Array<studio.Problem>>;

export function CheckWorkflow(arg1:string,arg2:doc.Workflow):Promise<Array<studio.Problem>>;

export function Choose():Promise<studio.Project>;

export function Initial():Promise<studio.Project>;

export function Project():Promise<studio.Project>;

export function RenderAction(arg1:doc.Action):Promise<string>;

export function RenderWorkflow(arg1:doc.Workflow):Promise<string>;

export function Run(arg1:string,arg2:doc.Workflow,arg3:studio.RunOptions):Promise<studio.RunResult>;

export function SaveAction(arg1:string,arg2:doc.Action):Promise<void>;

export function SaveWorkflow(arg1:string,arg2:doc.Workflow):Promise<void>;

export function Stop():Promise<void>;

export function Workflow(arg1:string):Promise<doc.Workflow>;
